### ISSUE TITLE
Problems compiling Chapter 2

### ISSUE THREAD

**Issue by chebaperez** [PacktPublishing/Mastering-OpenCV3-Second-Edition#1]
Hello,

I'm trying to compile Chapter 2 (Structure from Motion) with OpenCV 3.2 and throws me the following error: "GPUSURFFeatureMatcher.h:10:31: fatal error: opencv2/gpu/gpu.hpp: No such file or directory"

Apparently this code was written for previous versions of OpenCV 3. However the book title indicates the version is OpenCV 3. Even in the description of this repository, it is recommended to use version 3.1.0.

I bought the book mainly for chapter 2. So, there is updated version of chapter 2 which works with OpenCV 3?

Thank you.

**Comment by WillieMaddox** [comment]
I get the same error.  Why is OpenCV2 code being used in an OpenCV3 book?  Chapter07 also has instances of gpu.hpp.

```bash
maddoxw@devbox:~/Mastering-OpenCV3-Second-Edition$ grep -nir gpu.hpp
Chapter07/iPhoneAR/Example_MarkerBasedAR/opencv2.framework/Versions/A/Headers/videostab/optical_flow.hpp:50:#  include "opencv2/gpu/gpu.hpp"
Chapter07/iPhoneAR/Example_MarkerBasedAR/opencv2.framework/Versions/A/Headers/stitching/detail/matchers.hpp:51:#include "opencv2/gpu/gpu.hpp"
Chapter07/iPhoneAR/Example_MarkerBasedAR/opencv2.framework/Versions/A/Headers/stitching/detail/warpers.hpp:50:# include "opencv2/gpu/gpu.hpp"
Chapter02/GPUSURFFeatureMatcher.h:10:#include <opencv2/gpu/gpu.hpp>
Chapter02/main.cpp:21:#include <opencv2/gpu/gpu.hpp>
Chapter02/OFFeatureMatcher.cpp:15:#include <opencv2/gpu/gpu.hpp>
Chapter02/MultiCameraPnP.cpp:17:#include <opencv2/gpu/gpu.hpp>
```

Disappointing...

**Comment by zhouhao27** [comment]
Same for chapter 03. Still using opencv2 code.

**Comment by frankneumann** [comment]
Also from my experience the chapter 2 example works only using OpenCV2. Even under OpenCV2 it requires some small adaptations.

**Comment by AurobindoKar** [comment]
Hi,

I am closing the issue.
In case the issue still persists, feel free to reopen it.

Thanks
