### ISSUE TITLE
sfm examples are old

### ISSUE THREAD

**Issue by shanmukhananda** [PacktPublishing/Mastering-OpenCV3-Second-Edition#2]
SFM examples mentioned in Chapter02 is taken from first edition of the text book.
Second edition of the text book uses many predefined OpenCV APIs, explains the use of Cerers for Bundle Adjustment, but I don't see these examples in this repo. 
Small project for SFM example as explained in 2nd edition of text book would be very helpful, and easy to understand.

**Comment by ManikandanKurup-Packt** [comment]
Thank you for the feedback.
